framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
        transports:
            sync: 'sync://'
        routing:
            'App\Shared\Application\Command\Command': sync
