monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
            channels: ["app"]
when@test:
    monolog:
        handlers:
            main:
                path: "%kernel.logs_dir%/error_test.log"