services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Integration\:
        resource: '../tests/Integration/*'

    App\Tests\Integration\Item\Steps\ItemSteps:
        arguments:
            $projectDir: '%kernel.project_dir%'